# #66DaysOfData-Day4
## Numpy Multidimesional Arrays

In [1]:
import numpy as np

In [6]:
array_2d = np.array([[1,2,3,4,5],
           [11,12,13,14,15]])

print(array_2d)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [7]:
print(array_2d.shape)

(2, 5)


In [13]:
print(array_2d[:,1:2])

[[ 2]
 [12]]


In [12]:
array_2d[0,0]

1

In [14]:
array_2d[:,-1:-3]

array([], shape=(2, 0), dtype=int32)